machine:
    services:
        - docker

dependencies:
    override:

test:
    override:
        - docker pull harrisonjg/se_demux_to_bam_bai_denovo
        - curl -fsSL get.nextflow.io | bash
        - ./nextflow run se_demux_to_bam_bai_denovo --in ./data/sample1.fastq --key data/samplekey.csv --path_out ./data/ --dbpath ./contaminants/ --mode denovo --threshold 4


