version: 2.0
executors: 
 docker-executor:
   docker:
         - image: harrisonjg/nf_se_demux_to_bam_bai_denovo
         - image: nextflow/nextflow
jobs:
  run_nextflow:
    executor: docker-executor
    steps:
      - checkout    
      - run:    
          name: Run the workflow
          command: |
            nextflow run se_demux_to_bam_bai_denovo --in ./data/sample1.fastq --key data/samplekey.csv --path_out ./data/ --dbpath ./contaminants/ --mode denovo --threshold 4 -with-docker harrisonjg/nf_se_demux_to_bam_bai_denovo
workflows:
 myworkflow:
   jobs:
  - run_nextflow
