version: 2.1
jobs:
  se_demux_to_bam_bai_denovo:
    docker:
      - image: harrisonjg/nf_se_demux_to_bam_bai_denovo
    steps:
      - checkout
      - run: |
          wget -qO- https://get.nextflow.io | bash
          ./nextflow run se_demux_to_bam_bai_denovo --in ./data/sample1.fastq --key data/samplekey.csv --path_out ./data/ --dbpath ./contaminants/ --mode denovo --threshold 4
          
workflows:
  my-custom-workflow:
    jobs:
      - se_demux_to_bam_bai_denovo

