version: 2.1
executors:
  my-custom-executor:
    machine: 
	- ubuntu-2004:202111-02
    docker:
      - image: harrisonjg/nf_se_demux_to_bam_bai_denovo
jobs:
  se_demux_to_bam_bai_denovo:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          curl -fsSL get.nextflow.io | bash
          ./nextflow run se_demux_to_bam_bai_denovo --in ./data/sample1.fastq --key data/samplekey.csv --path_out ./data/ --dbpath ./contaminants/ --mode denovo --threshold 4
          
workflows:
  my-custom-workflow:
    jobs:
      - se_demux_to_bam_bai_denovo

